CRAFTERCMS-1797
craftercms/studio pull request #1056
Opened 2018-02-26 19:17 UTC by dejan-brkic

Implemented new Dependency Service

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/1797

2018-02-27 21:57 UTC, sumerjabri requested changes
Ping me to discuss as needed.

2018-02-27 21:57 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/impl/v1/content/pipeline/ExtractAssetDependencyProcessor.java
>              if (isCss || isJs || isTemplate) {
Would it make sense to just say: if the asset is textual, then try to extract dependencies?

2018-02-27 21:57 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java
>              String content = getContentAsString(site, movePath);
This is a problem. We're loading a piece of content of unknown size to RAM. Let's discuss.

We should also find other places that we load content into RAM and discuss.

2018-02-27 21:57 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/impl/v1/service/dependency/DependencyServiceImpl.java
> +    private void insertDependencies(List<DependencyEntity> dependencyEntities) {
Rename to insertDependenciesIntoDatabase? (in our continued mission to make clearer method names...)

2018-02-28 15:18 UTC, sumerjabri commented
@dejan-brkic also, please fix the Codacy issues you can fix.

2018-02-28 20:15 UTC, dejan-brkic commented
Fixed code review requests. Fixed codacy issues

2018-03-01 03:16 UTC, sumerjabri commented
Please these Codacy issues (click on show more in Codacy to see these):
```
src/main/java/org/craftercms/studio/impl/v1/content/pipeline/ExtractAssetDependencyProcessor.java
Avoid unused imports such as 'java.util.List'
20
import java.util.List;
Avoid unused imports such as 'java.util.regex.Matcher'
21
import java.util.regex.Matcher;
Avoid unused imports such as 'java.util.regex.Pattern'
22
import java.util.regex.Pattern;
src/main/java/org/craftercms/studio/impl/v1/content/pipeline/ExtractDependencyProcessor.java
Avoid unused imports such as 'org.dom4j.Document'
28
import org.dom4j.Document;
Avoid unused imports such as 'java.util.HashMap'
30
import java.util.HashMap;
Avoid unused imports such as 'java.util.Map'
31
import java.util.Map;
Avoid unused imports such as 'java.util.Set'
32
import java.util.Set;
src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
Avoid unused local variables such as 'content'.
1430
InputStream content = contentRepository.getContent(site, path);
src/main/java/org/craftercms/studio/impl/v1/service/workflow/WorkflowServiceImpl.java
Avoid unused local variables such as 'id'.
655
String id = site + ":" + user + ":" + request;
```

2018-03-01 15:40 UTC, dejan-brkic commented
Codacy fixes

2018-03-02 20:16 UTC, merged