Add CORS support for the API requests
craftercms/studio pull request #1381
Opened 2018-12-03 22:42 UTC by jdrossl

https://github.com/craftercms/craftercms/issues/2674

2018-12-03 23:00 UTC, sumerjabri commented
@jdrossl please also send a PR for `studio-config-override.yaml` in `craftercms` to allow the user to override/make changes.

2018-12-03 23:04 UTC, jdrossl commented
@sumerjabri I don't think we need to add them there to allow overriding, any property can be added if needed

2018-12-05 17:01 UTC, sumerjabri requested changes
Please also add these to the override file in `craftercms` with the comments that you're going to add here. Make sure it's commented out in the override.

The point of the override is to allow some orgs to make updates to tighten things up if required.

2018-12-05 17:01 UTC, sumerjabri commented on src/main/resources/crafter/studio/studio-config.yaml
> +studio.cors.disable: false
Please document these fields (one comment per field above the field).

2018-12-05 21:24 UTC, avasquez614 approved these changes

2018-12-05 22:09 UTC, sumerjabri approved these changes

2018-12-05 22:09 UTC, merged