CRAFTERCMS-2643
craftercms/studio pull request #1467
Opened 2019-02-11 20:33 UTC by dejan-brkic

fixed content type definition and upgrade

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/2643

2019-02-12 14:05 UTC, jdrossl reviewed
I think we also need to add upgrade operations to update the `sample-form-control-rte-setup.xml` & `rte-setup.xml` files according to the original PR https://github.com/craftercms/studio/pull/1365/files

2019-02-12 14:05 UTC, jdrossl commented on src/main/resources/crafter/studio/upgrade/pipelines.yaml
> +        nextVersion: 3
Please remember to update the version in the file for all blueprints

2019-02-14 14:24 UTC, jdrossl requested changes

2019-02-14 14:24 UTC, jdrossl commented on src/main/resources/crafter/studio/upgrade/pipelines.yaml
> +      nextVersion: 3.1.0.4
Please update `studio_version.xml` in the blueprints to match this version

2019-02-26 19:51 UTC, sumerjabri commented
@dejan-brkic bump

2019-03-14 22:38 UTC, dejan-brkic commented
fixed PR

2019-03-19 19:09 UTC, sumerjabri commented
Closing because it's a bit messy with too many merges.

2019-03-19 19:09 UTC, closed without merging