CRAFTERCMS-2982
craftercms/studio pull request #1521
Opened 2019-03-22 18:03 UTC by dejan-brkic

Update Audit API with filter options

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/2982

2019-03-22 20:32 UTC, sumerjabri requested changes
I also updated the design document and the filter-bys, let's discuss and agree on a final design. (The updates were necessary after a deeper discussion with Russ.)

2019-03-22 20:32 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +          description: Site ID - optional for super admin user, otherwise required
Please add `site name`.
Please also add `cluster node id`.

2019-03-25 15:15 UTC, dejan-brkic commented
Updated API docs

2019-03-25 15:25 UTC, sumerjabri approved these changes

2019-03-25 15:25 UTC, merged