CRAFTERCMS-2357
craftercms/studio pull request #1558
Opened 2019-04-09 20:32 UTC by dejan-brkic

added missing library

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/2357

2019-04-09 22:59 UTC, sumerjabri requested changes

2019-04-09 22:59 UTC, sumerjabri commented on pom.xml
> +            <version>1.9.22</version>
Please externalize the version (see other deps).

2019-04-10 13:49 UTC, sumerjabri commented
@dejan-brkic @avasquez614 note the Snyk report. What can we do to address that?

2019-04-10 14:19 UTC, avasquez614 commented
@sumer @dejan-brkic Probably include the latest Xerces like the report indicates.

2019-04-10 20:09 UTC, sumerjabri approved these changes

2019-04-10 20:14 UTC, avasquez614 approved these changes

2019-04-11 13:33 UTC, merged