CRAFTERCMS-3063
craftercms/studio pull request #1574
Opened 2019-04-22 18:17 UTC by dejan-brkic

Added content type api v2

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/3063

2019-04-23 13:26 UTC, sumerjabri requested changes

2019-04-23 13:26 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +      summary: Get content types
What permissions are needed here? Must have a role in the site (any role), right?

2019-04-23 13:26 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +      description: 'Required Permission: "CREATE_CONTENT_TYPE"'
Permission: must be a: developer or admin, right?

2019-04-23 13:26 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +        - content type
Permission: developer or admin?

2019-04-23 13:26 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +    ContentType:
Let's review this section together.

2019-04-23 14:23 UTC, avasquez614 requested changes

2019-04-23 14:23 UTC, avasquez614 commented on src/main/api/2/studio-api-2.yaml
> +        - name: class
Maybe `category` is a better name, instead of `class`? Just throwing it out there

2019-04-23 14:23 UTC, avasquez614 commented on src/main/api/2/studio-api-2.yaml
> +          description: Target path where content type will be used
Not really understand what is this path for, this API returns all content types, why is the path needed?

2019-04-23 14:23 UTC, avasquez614 commented on src/main/api/2/studio-api-2.yaml
> +      parameters:
We're missing the `offset`, `limit` and `sort` parameters.

2019-04-24 16:50 UTC, russdanner approved these changes
No additional feedback at this time

2019-05-15 14:17 UTC, sumerjabri requested changes
Please address issues listed and add permissions to all APIs (most have it already, but not all).

2019-05-15 14:17 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +          description: Target path where content type will be used
Limit the results to content types available for creation at targetPath

2019-05-15 14:17 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +        - name: path
targetPath

2019-07-08 18:18 UTC, sumerjabri commented
To be revisited.

2019-07-08 18:18 UTC, closed without merging