CRAFTERCMS-3070
craftercms/studio pull request #1583
Opened 2019-04-30 15:41 UTC by dejan-brkic

Added Repository API v2

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/3070

2019-05-14 18:39 UTC, sumerjabri requested changes
Add permissions to all API calls.

2019-05-14 18:39 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +                  description: Remote repository branch to pull from
Add ability to specify merge strategy: https://www.git-scm.com/docs/git-pull#Documentation/git-pull.txt--Xltoptiongt

2019-05-14 18:39 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +        '500':
Add `409` and return the git conflict message. Indicate that the user must contact an admin.

2019-05-14 18:39 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +        '500':
Add `409` and indicate git conflict and the user should notify the administrator.

2019-05-14 18:39 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +                  description: Remote repository branch to push to
Add support for `-f` `--force` to force push to remote. https://www.git-scm.com/docs/git-push#Documentation/git-push.txt--f

2019-05-14 18:39 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +  /repository/rebuild_databese:
Please fix typo in `databases`

2019-05-14 18:43 UTC, sumerjabri requested changes

2019-05-14 18:43 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +    RemoteInfo:
Change to `RemoteRepositoryInfo`

2019-05-14 18:43 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +  /repository/list_remotes:
Add an empty line above.

2019-05-27 18:50 UTC, dejan-brkic commented
Repository API v2

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/3070

2019-05-29 16:12 UTC, avasquez614 requested changes

2019-05-29 16:12 UTC, avasquez614 commented on src/main/java/org/craftercms/studio/impl/v2/service/repository/RepositoryManagementServiceImpl.java
> +    public boolean removeRemote(String siteId, String remoteName) throws CryptoException {
Isn't this missing the `@ProtectedResourceId(SITE_ID_RESOURCE_ID)`?

2019-05-29 17:53 UTC, sumerjabri approved these changes

2019-05-29 17:56 UTC, avasquez614 approved these changes

2019-05-29 18:32 UTC, merged