CRAFTERCMS-2812
craftercms/studio pull request #1596
Opened 2019-05-20 17:07 UTC by dejan-brkic

CMIS API v2 implemented

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/2812

2019-05-21 15:38 UTC, jdrossl approved these changes

2019-05-21 19:09 UTC, avasquez614 requested changes

2019-05-21 19:09 UTC, avasquez614 commented on src/main/api/2/studio-api-2.yaml
> +      description: 'Required permissions: "Read", "Write", "Create Content"'
isn't the permission `list_cmis`?

2019-05-21 19:09 UTC, avasquez614 commented on src/main/api/2/studio-api-2.yaml
> +      description: 'Required permissions: "Read", "Write", "Create Content"'
isn't the permission `search_cmis`?

2019-05-21 19:09 UTC, avasquez614 commented on src/main/api/2/studio-api-2.yaml
> +      description: 'Required permissions: "Read", "Write", "Create Content"'
isn't the permission `clone_content_cmis`?

2019-05-21 19:09 UTC, avasquez614 commented on src/main/api/2/studio-api-2.yaml
> +      description: 'Required permissions: "Read", "Write", "Create Content"'
isn't the permission `upload_content_cmis`?

2019-05-22 14:47 UTC, avasquez614 approved these changes

2019-05-22 20:34 UTC, merged