CRAFTERCMS-3173
craftercms/studio pull request #1618
Opened 2019-06-11 17:43 UTC by dejan-brkic

Quick create implementation

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/3173

2019-06-11 18:55 UTC, sumerjabri requested changes

2019-06-11 18:55 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/api/v2/service/content/internal/ContentTypeServiceInternal.java
> +    List<QuickCreateItem> getQuickCreatableContentTypes(String siteId);
JavaDoc

2019-06-11 18:55 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/api/v2/service/content/ContentService.java
> +    List<QuickCreateItem> getQuickCreatableContentTypes(String siteId) throws SiteNotFoundException;
JavaDoc

2019-06-11 18:55 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/controller/rest/v2/ContentController.java
>      @GetMapping("/api/2/content/quick_create")
Change to:
`/api/2/content/list_quick_create_content`

2019-06-11 21:31 UTC, avasquez614 approved these changes

2019-06-12 15:14 UTC, sumerjabri approved these changes

2019-06-12 15:14 UTC, merged