CRAFTERCMS-2655
craftercms/studio pull request #1644
Opened 2019-06-21 17:49 UTC by dejan-brkic

Pull from remote allows merge options

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/2655

2019-06-24 18:32 UTC, sumerjabri commented
@jdrossl please validate the upgrade manager stuff.

2019-06-24 19:56 UTC, jdrossl requested changes

2019-06-24 19:56 UTC, jdrossl commented on src/main/resources/crafter/studio/upgrade/pipelines.yaml
> +        - type: dbVersionUpgrader
We have been forgetting to update the version in the create db script for a while, please add it

2019-06-24 19:56 UTC, jdrossl commented on src/main/webapp/repo-bootstrap/global/blueprints/1000_website_editorial/config/studio/workflow/notification-config.xml
> +    <version>2</version>
Please add the version for the other blueprints too, and remember to send a PR for video-center too

2019-06-25 14:19 UTC, jdrossl approved these changes

2019-06-25 14:19 UTC, merged