Add new asset controller:
craftercms/studio pull request #1687
Opened 2019-07-31 22:16 UTC by jdrossl

- Add new controller to serve site files as static resources

https://github.com/craftercms/craftercms/issues/3328

2019-08-02 15:13 UTC, sumerjabri commented
@jdrossl let's meet and discuss this in more detail.

2019-08-02 15:20 UTC, sumerjabri requested changes
Let's discuss.

2019-08-02 15:20 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +  /configuration/extension/file:
perhaps `/plugin` is better because it's not always a configuration nor an extension? (For example, it's a plugin to the form engine, like a picker)

Let's discuss.

2019-08-02 15:20 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +        - configuration
The same thing, perhaps we change it to `plugin`.

2019-08-02 15:20 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +        - name: siteId
This means the API is strictly extending sites only. Should we consider making the API more general to address:
- Organization <== we can hide that for now
- Site being optional (so you can have a Main Menu plugin for example

2019-08-02 15:20 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +        - name: module
Why is this needed? This is a Studio API only, no?

2019-08-02 15:20 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +        - name: filename
Should we also allow the caller to ask for a plugin descriptor where we get the meta-data about it and not just files? Should it be in the same API definition or add another definition?

2019-08-05 15:50 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +  /configuration/extension/file:
Please make it `/plugin/file`

2019-08-05 15:51 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +        - name: siteId
Decision: Keep `siteId` required for now and change that when we're ready for global plugings.

2019-08-05 15:52 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +        - name: module
Decision: remove this.

2019-08-05 15:52 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +        - name: filename
Decision: Future feature.

2019-08-05 18:03 UTC, sumerjabri requested changes

2019-08-05 18:03 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/api/v2/service/config/ConfigurationService.java
> +    Resource getPluginFile(String siteId, String type, String plugin, String filename)
Any other exceptions for us to consider?

2019-08-05 18:03 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/api/v1/service/content/ContentService.java
> +    Resource getContentAsResource(String site, String path) throws ContentNotFoundException;
Other exceptions?

2019-08-05 18:03 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/controller/rest/v2/ConfigurationController.java
> +import java.io.InputStream;
Why add this?

2019-08-05 18:03 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/impl/v1/service/configuration/ServicesConfigImpl.java
> +             siteConfig.setPluginFolderPattern(configNode.valueOf("plugin-folder-pattern"));
Please use a constant for the literal string. You can ask Dejan for where to put that.

2019-08-05 19:25 UTC, jdrossl commented on src/main/java/org/craftercms/studio/api/v1/service/content/ContentService.java
> +    Resource getContentAsResource(String site, String path) throws ContentNotFoundException;
Since the service just returns the content of the file without any processing the only exception that can be found is that one

2019-08-05 19:27 UTC, jdrossl commented on src/main/java/org/craftercms/studio/controller/rest/v2/ConfigurationController.java
> +import java.io.InputStream;
It was already there, the IDE just move it to the top of the imports

2019-08-05 19:28 UTC, jdrossl commented on src/main/java/org/craftercms/studio/api/v2/service/config/ConfigurationService.java
> +    Resource getPluginFile(String siteId, String type, String plugin, String filename)
This is the only exception that the service can throw (except for runtime exceptions but those are already handled to return 500)

2019-08-05 20:17 UTC, sumerjabri approved these changes

2019-08-05 20:18 UTC, merged