[studio-ui] Template Code Examples #3430
craftercms/studio pull request #1737
Opened 2019-09-10 16:57 UTC by jvega190

https://github.com/craftercms/craftercms/issues/3430

2019-09-11 20:17 UTC, rart approved these changes

2019-09-13 13:51 UTC, sumerjabri commented on src/main/webapp/repo-bootstrap/global/configuration/samples/sample-code-editor-config.xml
> +  <theme>light</theme>       <!-- default theme: ligth | dark -->
Is the `theme` overridable? If so, why isn't it spec'd out in the overrides?

2019-09-13 14:13 UTC, sumerjabri requested changes
Include `<theme>` in all blueprint examples.

2019-09-13 21:33 UTC, jvega190 commented
@sumerjabri Done. Theme added

2019-09-14 09:29 UTC, rart requested changes
Please reformat the commented snippets as open comment, line break, snippet, line break, close comment.

e.g.
```xml
<!--
<snippet>
  ...
</snippet>
-->
```

2019-09-17 23:02 UTC, rart approved these changes

2019-09-18 15:55 UTC, sumerjabri requested changes

2019-09-18 15:55 UTC, sumerjabri commented on src/main/webapp/repo-bootstrap/global/blueprints/2000_headless_store/config/studio/code-editor-config.xml
> +  <theme>light</theme>       <!-- default theme: ligth | dark -->
`light` is misspelled in the comments.

Also, why is that not commented out and use the default inherited setting?

2019-09-18 19:27 UTC, sumerjabri approved these changes

2019-09-18 19:28 UTC, merged