Update create site:
craftercms/studio pull request #1761
Opened 2019-10-02 14:33 UTC by jdrossl

- remote name parameter is now optional, defaults to `origin`

https://github.com/craftercms/craftercms/issues/3479

2019-10-02 18:18 UTC, sumerjabri requested changes
Should we also update the docs to indicate that this param is now optional?

2019-10-02 18:18 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/api/v2/utils/StudioConfiguration.java
> +    String REPO_REMOTE_NAME = "studio.repo.siteRemoteName";
Add the word DEFAULT.

Maybe: REPO_DEFAULT_REMOTE_NAME

2019-10-02 18:18 UTC, sumerjabri commented on src/main/resources/crafter/studio/studio-config.yaml
> +studio.repo.siteRemoteName: origin
studio.repo.defaultRemoteName

2019-10-02 18:54 UTC, jdrossl commented
PR for the doc https://github.com/craftercms/docs/pull/849

2019-10-04 13:40 UTC, sumerjabri approved these changes

2019-10-04 13:40 UTC, merged