New create site API for Marketplace:
craftercms/studio pull request #1796
Opened 2019-10-22 18:06 UTC by jdrossl

- Marketplace service handles validations and triggers the create

2019-10-22 19:28 UTC, dejan-brkic requested changes

2019-10-22 19:28 UTC, dejan-brkic commented on src/main/java/org/craftercms/studio/impl/v2/service/marketplace/MarketplaceServiceImpl.java
> +    public Map<String, Object> getDescriptor(String id, Version version) throws MarketplaceException,
Public methods of v2 services should be protected with permissions

2019-10-22 19:28 UTC, dejan-brkic commented on src/main/java/org/craftercms/studio/impl/v2/service/marketplace/MarketplaceServiceImpl.java
> +    public void createSite(CreateSiteRequest request) throws RemoteRepositoryNotFoundException,
Public methods of v2 services should be protected with permissions

2019-10-22 20:28 UTC, sumerjabri requested changes

2019-10-22 20:28 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +  /marketplace/create_site:
Why not `/site/create_site_from_marketplace`?

`/site/` becomes the new root for API2 site operations.

My issue with `/marketplace` is that it's misleading thinking this is the marketplace of Studio when it's just create site API specialized.

2019-10-22 20:36 UTC, jdrossl commented on src/main/api/2/studio-api-2.yaml
> +  /marketplace/create_site:
I added it there to call directly the marketplace service and avoid having to change the other service, my idea was to wrap the site service so they continue to be independent (mp can change without changing site service and the other way around)

2019-10-22 20:51 UTC, jdrossl commented on src/main/api/2/studio-api-2.yaml
> +  /marketplace/create_site:
If you are only worried about the URL then we can move it to the `SitesController` and still call the MP service. Let me know if that works or if you want to talk about it

2019-10-23 16:04 UTC, dejan-brkic approved these changes

2019-10-23 18:34 UTC, sumerjabri approved these changes

2019-10-23 18:34 UTC, merged