Engine Plugins:
craftercms/studio pull request #1884
Opened 2020-02-13 22:15 UTC by jdrossl

- Add new API for getting & installing plugins in sites

2020-02-26 20:43 UTC, sumerjabri requested changes

2020-02-26 20:43 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +        '500':
Add 403?

2020-02-26 20:43 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +        '409':
Add 403?

2020-02-26 20:43 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +    FileRecord:
Let's discuss this part over a call.

2020-02-26 20:43 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/model/rest/ApiResponse.java
>              new ApiResponse(50000, "CMIS server is unreachable", "Advise the user that the CMIS server is not " +
Was this added to the list of error codes in the OAS docs?

2020-02-26 20:43 UTC, sumerjabri commented on src/main/resources/crafter/studio/studio-config.yaml
> +  - scripts/filters: scripts/filters
Let's discuss.

2020-02-26 21:29 UTC, jdrossl commented on src/main/api/2/studio-api-2.yaml
> +        '500':
Right now there are no permissions defined for these new operations, any authenticated user can execute them

2020-02-27 16:15 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/impl/v2/service/marketplace/MarketplaceServiceImpl.java
> +    //TODO: Add specific permissions?
Permission is "site member"

2021-01-16 03:50 UTC, rart reviewed
Looks good.

The only feedback I’ve got is if we could, for the `/installed` endpoint, use the same response model as marketplace search ([MarketplacePlugin](https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.1#/MarketplacePlugin), [GitMarketplacePlugin](https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.1#/GitMarketplacePlugin)) which includes media, compatibility, and other plugin details. This would allow for a more visual and rich listing and details UI. The properties of the new model are of use too, so maybe combine the models, or nest them, or be able to relate them somehow.

Question: will local site plugins – i.e. plug-ins that were developed and deployed with the site, without coming from the marketplace – also be indexed, returned and managed by these APIs? An additional property to flag whether a record came from marketplace or is “local” would be appropriate.

2021-01-18 15:22 UTC, jdrossl commented
@rart
Local plugins developed as part of the site will not be returned by this API, only plugins installed from the marketplace.

About merging the response I don't think it's a good idea for now, but we can consider it later. The reason is that this API returns data from a file stored in the site, if there are 10 plugins installed we would need to query the MP for each one of the descriptors.

2021-01-18 15:29 UTC, rart commented
Does the info of the MarketplacePlugin models come from the yaml file or it comes from some sort of database? Installed plugins have their yaml file, right? Could we extract directly from the yaml?

2021-01-18 15:57 UTC, jdrossl commented
We are not storing the descriptors right now

2021-02-02 19:38 UTC, sumerjabri requested changes
Roles allowed to install plugins:
* Developers
* Admins

Roles allowed to list plugins:
* Everyone in the site

Switch 4.0.0.1 to 4.0.0.4 for API OAS, UM, and other places.

Remove sha512 from FileRecord in OAS

2021-02-05 17:41 UTC, sumerjabri requested changes

2021-02-05 17:41 UTC, sumerjabri commented on src/main/api/2/studio-api-2.yaml
> +      operationId: getInstalledPlugins
Please add required permission in the spec, like:

```
description: 'Required Permission: "XXYYZZ"'
```

2021-02-11 15:51 UTC, sumerjabri approved these changes

2021-02-11 15:51 UTC, merged