Add Blob Storage:
craftercms/studio pull request #1902
Opened 2020-03-03 20:16 UTC by jdrossl

- Proxy operations to read/write/publish content to the repository
- Support for AWS S3 Blob Store

https://github.com/craftercms/craftercms/issues/3744

2020-03-03 23:18 UTC, avasquez614 requested changes

2020-03-03 23:18 UTC, avasquez614 commented on src/main/java/org/craftercms/studio/impl/v2/repository/blob/BlobAwareContentRepository.java
> +            return false;
Not logging exceptions?

2020-03-03 23:18 UTC, avasquez614 commented on src/main/java/org/craftercms/studio/impl/v2/repository/blob/BlobStoreFactoryImpl.java
> +    public BlobStore getByPaths(String site, String[] paths) throws ServiceLayerException, ConfigurationException {
Why not use String... (varargs)?

2020-03-04 15:25 UTC, dejan-brkic approved these changes

2020-03-10 15:24 UTC, avasquez614 commented on src/main/java/org/craftercms/studio/impl/v2/repository/blob/BlobAwareContentRepository.java
> +            return false;
This is still not resolved. Can you explain why are you not logging the exception?

2020-03-10 15:41 UTC, avasquez614 approved these changes

2020-03-10 15:42 UTC, merged