Initial implementation of JWT:
craftercms/studio pull request #2320
Opened 2020-12-18 22:47 UTC by jdrossl

- Replace all authentication related code with Spring Security
- Implement HTTP Basic & JWT auth for the API
- Add new API for token management

https://github.com/craftercms/craftercms/issues/4429

2020-12-22 21:30 UTC, avasquez614 approved these changes

2021-02-01 20:57 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/impl/v2/security/listener/AuditLoginListener.java
> +            //TODO: Should we also record this events?
Please log.

2021-02-01 21:10 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/impl/v2/service/security/internal/AccessTokenServiceInternalImpl.java
> +                    .setRelaxVerificationKeyValidation() // TODO: Check if this is ok
Please remove per our discussion.

2021-02-01 21:17 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/impl/v2/service/security/internal/AccessTokenServiceInternalImpl.java
> +            jws.setAlgorithmHeaderValue(AlgorithmIdentifiers.HMAC_SHA512); // TODO: Choose an algorithm
Remove TODO

2021-02-01 21:17 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/impl/v2/service/security/internal/AccessTokenServiceInternalImpl.java
> +            jws.setDoKeyValidation(false); // TODO: Check if this is ok
Remove.

2021-02-01 21:21 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/impl/v2/service/security/internal/AccessTokenServiceInternalImpl.java
> +            // TODO: Choose algorithms
Remove todo

2021-02-01 21:23 UTC, sumerjabri requested changes
Please address the notes.

2021-02-02 15:53 UTC, sumerjabri commented on src/main/webapp/default-site/scripts/rest/api/1/security/login.post.groovy
> +result.message = "This API has been deprecated"
This API has been replaced by a new login mechanism via JWT, please review the documentation.

2021-02-02 16:16 UTC, sumerjabri approved these changes

2021-02-02 16:17 UTC, merged