[4585] [studio] Synchronized block in getOperations causes possible thread based locks on lockItem repository action
craftercms/studio pull request #2466
Opened 2021-03-18 16:13 UTC by dejan-brkic

### Ticket reference or full description of what's in the PR

2021-03-18 20:14 UTC, sumerjabri commented
This PR seems to contain other stuff not related to the ticket.

2021-03-18 20:15 UTC, sumerjabri requested changes
This PR seems to contain other stuff not related to the ticket.

2021-03-18 20:34 UTC, dejan-brkic commented
> This PR seems to contain other stuff not related to the ticket.

Merge conflicts

2021-03-19 13:42 UTC, sumerjabri approved these changes

2021-03-19 13:42 UTC, merged