[4519] Nextify out of box blueprints - Update assets
craftercms/studio pull request #2507
Opened 2021-04-07 18:54 UTC by jvega190

https://github.com/craftercms/craftercms/issues/4519

2021-04-08 18:12 UTC, rart requested changes
Bad copyright in several places.

2021-04-08 18:12 UTC, rart commented on src/main/webapp/repo-bootstrap/global/blueprints/1000_website_editorial/site/taxonomy/categories.xml
>    ~
Please use right copy right. Year needs fixing and I think this is the previous copy text

2021-04-08 21:29 UTC, jvega190 commented
@rart here's the list of changes:
- Updated copyrights where needed
- Added the articles in proper new folders (2020, 2021)
- Added scss sources
- Added new font files (font awesome 5)
- Fixed merge problems (content, form-definitions and master branch newer commits)

2021-04-13 10:27 UTC, rart approved these changes

2021-04-13 13:16 UTC, merged