Fix for S3:
craftercms/studio pull request #2825
Opened 2022-01-10 19:19 UTC by jdrossl

- Support copy operation for large files

https://github.com/craftercms/craftercms/issues/5215

2022-01-10 19:33 UTC, avasquez614 requested changes

2022-01-10 19:33 UTC, avasquez614 commented on src/main/java/org/craftercms/studio/impl/v1/service/aws/AwsUtils.java
>      public static final int MIN_PART_SIZE = 5 * 1024 * 1024;
This constant seems to not be used

2022-01-10 19:33 UTC, avasquez614 commented on src/main/java/org/craftercms/studio/impl/v1/service/aws/AwsUtils.java
> +    public static final int COPY_PART_SIZE = 1024 * 1024 * 1024;
This constant seems to not be used

2022-01-10 19:33 UTC, avasquez614 commented on src/main/java/org/craftercms/studio/impl/v1/service/aws/AwsUtils.java
> +        if (objectSize >= 5L * 1024L * 1024L * 1024L) {
Shouldn't this use a constant?

2022-01-10 19:40 UTC, jdrossl commented on src/main/java/org/craftercms/studio/impl/v1/service/aws/AwsUtils.java
>      public static final int MIN_PART_SIZE = 5 * 1024 * 1024;
it is used in other classes

2022-01-10 19:41 UTC, jdrossl commented on src/main/java/org/craftercms/studio/impl/v1/service/aws/AwsUtils.java
> +    public static final int COPY_PART_SIZE = 1024 * 1024 * 1024;
it is used in other classes

2022-01-12 19:49 UTC, avasquez614 approved these changes

2022-01-12 19:51 UTC, merged