Fix format for dates on copy
craftercms/studio pull request #2851
Opened 2022-01-25 15:21 UTC by jdrossl

https://github.com/craftercms/craftercms/issues/5268

2022-01-25 15:24 UTC, sumerjabri requested changes
Can this be made a common utility function that's used wherever this is needed to avoid this type of error in the future?

2022-01-25 15:40 UTC, jdrossl commented
This is the only place so far where this format is required, but yeah in the future it is possible to reuse it

2022-01-25 19:14 UTC, sumerjabri commented
Please centralize it in the utils/helper class as a static method, add Javadoc, and use the shared helper.

2022-01-26 22:43 UTC, sumerjabri approved these changes

2022-01-26 22:43 UTC, merged