[5331] [studio] Workflow States: Error in filter regex of Workflow States when adding '*' or '[' characters
craftercms/studio pull request #2903
Opened 2022-03-15 18:23 UTC by dejan-brkic

Added regex validation

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/5331

2022-03-15 21:19 UTC, sumerjabri requested changes

2022-03-15 21:19 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/controller/rest/v2/WorkflowController.java
> +    private boolean isPathRegexValid(String pathRegex) {
Is this going to return a 400 (invalid params) to the REST caller or will it silently fail?

2022-03-16 14:33 UTC, jdrossl approved these changes

2022-03-16 14:37 UTC, sumerjabri approved these changes

2022-03-16 14:37 UTC, merged