Add auto-repair for locked/corrupted git repos
craftercms/studio pull request #2995
Opened 2022-05-26 11:37 UTC by phuongnq

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/5600

The following PR must be checked and merged first: https://github.com/craftercms/commons/pull/304

2022-05-26 11:47 UTC, phuongnq commented
@avasquez614 To fix the case git is corrupted, I added a new parameter `Repository` to `RetryingRepositoryOperationFacadeImpl`:

```
@Override
    public <T> T call(Callable<T> gitCommand, Repository repository) throws Exception {
        return gitCommand.call();
    }
```

This is used to track Git repository path while catching the exception. Please let me know if this is OK or if we have a better way to do it.

2022-05-26 16:00 UTC, jdrossl requested changes

2022-05-26 16:00 UTC, jdrossl commented on src/main/java/org/craftercms/studio/impl/v2/repository/RepositoryStartupCleanup.java
> +            String gitLockKeySandbox = SITE_SANDBOX_REPOSITORY_GIT_LOCK.replaceAll(PATTERN_SITE, siteId);
It would be better to use the methods from the helper so that in the future we have this code in a single place, see: https://github.com/craftercms/studio/blob/02a7a6e2df3a49f29ac44efd9039abf8dafedbd9/src/main/java/org/craftercms/studio/api/v2/utils/GitRepositoryHelper.java#L1280

2022-05-26 18:52 UTC, sumerjabri commented
@phuongnq yes, you should reset the repo after removal of the index

2022-05-26 18:54 UTC, russdanner commented
The manual fix for the currupt repo is to run the following two commands:
```
rm .git/index
git reset --hard
 ```

2022-05-27 09:11 UTC, phuongnq commented on src/main/java/org/craftercms/studio/impl/v2/repository/RepositoryStartupCleanup.java
> +            String gitLockKeySandbox = SITE_SANDBOX_REPOSITORY_GIT_LOCK.replaceAll(PATTERN_SITE, siteId);
Fixed. Thank you!

2022-05-27 09:24 UTC, phuongnq commented
Updated to run `git reset --hard` after the deletion. Thank you!

2022-05-27 14:16 UTC, jdrossl approved these changes

2022-06-01 14:16 UTC, avasquez614 requested changes
- Index removal and repository reset should only happen on startup.
- We should do a `git clean` after the reset so new pending files are removed too.

2022-06-02 08:12 UTC, phuongnq commented
Updated to do both unlock and remove corrupted index at startup.
Steps for removing index:

```
git rm .git/index
git reset --hard
git clean --force
```

2022-06-02 14:31 UTC, avasquez614 requested changes

2022-06-02 14:31 UTC, avasquez614 commented on src/main/java/org/craftercms/studio/api/v2/utils/GitRepositoryHelper.java
> +                        logger.info(".git/index.lock is deleted from global repository '{}'", path);
This log entry should be part of the `GitUtils.unlock` method.

2022-06-02 16:21 UTC, jdrossl approved these changes

2022-06-03 04:30 UTC, phuongnq commented on src/main/java/org/craftercms/studio/api/v2/utils/GitRepositoryHelper.java
> +                        logger.info(".git/index.lock is deleted from global repository '{}'", path);
Fixed. Thank you!

2022-06-06 21:04 UTC, avasquez614 approved these changes

2022-06-06 21:04 UTC, sumerjabri approved these changes

2022-06-06 21:04 UTC, merged