[3.1] Support GitCli and use reset after a corruption
craftercms/studio pull request #2997
Opened 2022-05-27 10:04 UTC by phuongnq

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/5600

2022-05-27 14:17 UTC, jdrossl approved these changes

2022-06-01 14:16 UTC, avasquez614 requested changes
- Index removal and repository reset should only happen on startup.
- We should do a `git clean` after the reset so new pending files are removed too.

2022-06-02 09:17 UTC, phuongnq commented
Updated to do both unlock and remove corrupted index at startup.
Steps for removing index:

```
git rm .git/index
git reset --hard
git clean --force
```

2022-06-02 14:24 UTC, avasquez614 approved these changes

2022-06-02 14:49 UTC, merged