Populate gitlog table during site creation
craftercms/studio pull request #3003
Opened 2022-05-31 22:28 UTC by jdrossl

https://github.com/craftercms/craftercms/issues/5613

2022-05-31 22:48 UTC, avasquez614 requested changes

2022-05-31 22:48 UTC, avasquez614 commented on src/main/java/org/craftercms/studio/impl/v2/repository/GitContentRepository.java
> +            Iterable<RevCommit> gitlog = git.log().call();
`gitLog` (camel case)?

2022-05-31 22:55 UTC, avasquez614 approved these changes

2022-06-01 13:56 UTC, sumerjabri commented
@phuongnq FYI

2022-06-01 13:57 UTC, merged