Add group externally managed flag
craftercms/studio pull request #3165
Opened 2023-01-11 09:08 UTC by phuongnq

### Ticket reference or full description of what's in the PR
https://github.com/craftersoftware/craftercms/issues/483

2023-01-11 16:37 UTC, sumerjabri requested changes

2023-01-11 16:37 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/impl/v2/service/security/GroupServiceImpl.java
> +
Must also make sure we return to the UI the fact that a group is externally managed so it can disable the user's ability to make updates. Is that done already?

2023-01-11 22:19 UTC, jmendeza approved these changes

2023-01-12 03:02 UTC, phuongnq commented on src/main/java/org/craftercms/studio/impl/v2/service/security/GroupServiceImpl.java
> +
@sumerjabri Yes, we are returning `externallyManaged` flag (`true` or `false`) to UI. See screenshot:

![2023-01-12_10-01](https://user-images.githubusercontent.com/2996543/211965782-c978064b-4077-449b-886e-b64cff8e6d97.png)

2023-01-12 15:10 UTC, sumerjabri approved these changes

2023-01-12 15:10 UTC, merged