Validations refactor
craftercms/studio pull request #3166
Opened 2023-01-12 00:31 UTC by jmendeza

https://github.com/craftersoftware/craftercms/issues/470

2023-01-13 21:06 UTC, sumerjabri requested changes

2023-01-13 21:06 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/model/rest/content/UnlockItemByPathRequest.java
> +    @Size(max = 4)
What does this limit?

2023-01-13 21:06 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/model/rest/content/UnlockItemByPathRequest.java
> +    @Size(min = 2)
Why 2?

2023-01-13 21:06 UTC, sumerjabri commented on src/main/resources/crafter/commons/validation/errors_es.properties
> +# Copyright (C) 2007-2022 Crafter Software Corporation. All Rights Reserved.
What's this file about?

2023-01-14 00:17 UTC, jmendeza commented on src/main/resources/crafter/commons/validation/errors_es.properties
> +# Copyright (C) 2007-2022 Crafter Software Corporation. All Rights Reserved.
This was a local test, I removed it

2023-01-14 00:21 UTC, jmendeza commented on src/main/java/org/craftercms/studio/model/rest/content/UnlockItemByPathRequest.java
> +    @Size(max = 4)
It was a test. I cleaned it up.

2023-01-14 00:21 UTC, jmendeza commented on src/main/java/org/craftercms/studio/model/rest/content/UnlockItemByPathRequest.java
> +    @Size(min = 2)
It was a test. I cleaned it up.

2023-01-14 00:47 UTC, jmendeza commented
This PR depends on https://github.com/craftercms/engine/pull/612

2023-01-16 15:34 UTC, sumerjabri approved these changes

2023-01-16 15:37 UTC, sumerjabri approved these changes

2023-01-16 15:38 UTC, merged