Delete site API v2
craftercms/studio pull request #3241
Opened 2023-05-18 23:50 UTC by jmendeza

https://github.com/craftercms/craftercms/issues/6061
Delete site API v2

2023-05-24 20:04 UTC, sumerjabri requested changes
Please make DRAFT until 4.1.0 is out and tagged. Please also fix the issues noted.

2023-05-24 20:04 UTC, sumerjabri commented on src/main/resources/crafter/studio/database/createDDL.sql
> +INSERT INTO _meta (version, studio_id) VALUES ('4.1.3', UUID()) ;
4.2.0?

2023-05-24 20:04 UTC, sumerjabri commented on src/main/resources/crafter/studio/upgrade/pipelines.yaml
> +        nextVersion: 4.1.3
4.2.0?

2023-06-08 23:01 UTC, jmendeza commented on src/main/resources/crafter/studio/database/createDDL.sql
> +INSERT INTO _meta (version, studio_id) VALUES ('4.1.3', UUID()) ;
Done

2023-06-08 23:01 UTC, jmendeza commented on src/main/resources/crafter/studio/upgrade/pipelines.yaml
> +        nextVersion: 4.1.3
Done

2023-08-29 12:59 UTC, sumerjabri approved these changes

2023-08-29 13:00 UTC, merged