Add get content type(s) API v2
craftercms/studio pull request #3275
Opened 2023-06-22 07:17 UTC by phuongnq

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/6061

2023-06-22 07:19 UTC, phuongnq commented
Sample usages:

```
GET http://localhost:8080/studio/api/2/configuration/get_content_type?siteId=ed&contentTypeId=/page/home
```

```
GET http://localhost:8080/studio/api/2/configuration/get_content_types?siteId=ed&path=/site/website/articles/
```

2023-06-30 23:15 UTC, jmendeza requested changes

2023-06-30 23:15 UTC, jmendeza commented on src/main/java/org/craftercms/studio/controller/rest/v2/ConfigurationController.java
> +    @GetMapping("/get_content_type")
Let's consider adding a ContentTypeController

List `/content-types`
Get `/content-types?siteId=site&contentTypeId=component/something`

Thoughts @sumerjabri ?

2023-06-30 23:15 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v2/repository/GitContentRepository.java
> +    public RepositoryItem[] getContentChildren(String site, String path) {
This method is too long, please break it down into smaller pieces

2023-06-30 23:15 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v2/service/content/internal/ContentTypeServiceInternalImpl.java
> +        if (contentTypeConfig == null) {
Please use guard statements when possible to reduce indentation levels.
e.g.:
if (contentTypeConfig != null) {
    return contentTypeConfig;
}
...
...

2023-06-30 23:15 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v2/service/content/internal/ContentTypeServiceInternalImpl.java
> +        // TODO: SJ: Add general lock service lock around this key to avoid having more than one thread do this work
Please let's take care of this TODOs (or let's discuss if still relevant) when porting code from v1

2023-06-30 23:15 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v2/service/content/internal/ContentTypeServiceInternalImpl.java
> +        if (folders != null) {
Please use guard statements

2023-06-30 23:15 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v2/service/content/internal/ContentTypeServiceInternalImpl.java
> +        if (CollectionUtils.isNotEmpty(allContentTypes)) {
Please use guard statements

2023-06-30 23:15 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v2/service/content/internal/ContentTypeServiceInternalImpl.java
> +    protected boolean isUserAllowed(Set<String> userRoles, ContentTypeConfigTO item) {
@sumerjabri should we consider updating this functionality to check for permissions instead of roles?

2023-06-30 23:15 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v2/service/content/internal/ContentTypeServiceInternalImpl.java
> +        if (nodes != null && nodes.size() > 0) {
Please use guard statements
Consider using `CollectionUtils.isEmpty` in these scenarios

2023-06-30 23:15 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v2/service/content/internal/ContentTypeServiceInternalImpl.java
> +        if (nodes != null && nodes.size() > 0) {
Please use guard statements

2023-06-30 23:15 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v2/service/content/internal/ContentTypeServiceInternalImpl.java
> +        if (nodes != null) {
Please use guard statements

2023-06-30 23:15 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v2/service/content/internal/ContentTypeServiceInternalImpl.java
> +        if (Pattern.matches("/component/.*?", name)) {
Consider removing unnecessary `else`s

2023-10-11 00:53 UTC, jmendeza commented
Heads-up: We will be designing a content type API controller to handle this requests

2024-06-20 01:51 UTC, phuongnq commented
Close for now. Will revaluate in 5.0.0

2024-06-20 01:51 UTC, closed without merging