Duplicate site API (WIP)
craftercms/studio pull request #3323
Opened 2023-09-27 01:44 UTC by jmendeza

https://github.com/craftercms/craftercms/issues/6199
Duplicate site API

2023-09-28 17:12 UTC, jmendeza commented
Please notice this depends on https://github.com/craftercms/commons/pull/355 and https://github.com/craftercms/deployer/pull/396

2023-10-02 20:18 UTC, sumerjabri requested changes
Can a unit test be added to the Duplicate Site service? (or is that not doable?)

2023-10-02 22:17 UTC, jmendeza commented
> Can a unit test be added to the Duplicate Site service? (or is that not doable?)

Yes @sumerjabri , I will try to add some

2023-10-05 21:28 UTC, sumerjabri approved these changes

2023-10-05 21:29 UTC, merged