Add create folder API v2
craftercms/studio pull request #3382
Opened 2023-11-24 09:04 UTC by phuongnq

https://github.com/craftercms/craftercms/issues/6061

2023-11-27 17:28 UTC, jmendeza requested changes

2023-11-27 17:28 UTC, jmendeza commented on src/main/resources/crafter/studio/upgrade/pipelines.yaml
> +          nextVersion: 4.2.0.0
An extra `.0`?

2023-11-27 17:28 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v2/service/security/internal/UserServiceInternalImpl.java
> +    private ConfigurationService configurationService;
Can this be final?

2023-11-27 17:28 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v2/service/security/internal/UserServiceInternalImpl.java
> +    public UserServiceInternalImpl(UserDAO userDao , ConfigurationService configurationService,
Let's remove space before the comma

2023-11-27 17:28 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v2/utils/spring/security/messaging/StudioMessageSecurityExpressionRoot.java
>              }
Please take a look at recent changes in `SecurityService`. We have `isSiteMember` and `isSiteAdmin`, so we can drop dependency of this class on UserService

2023-11-27 18:53 UTC, phuongnq commented on src/main/java/org/craftercms/studio/impl/v2/service/security/internal/UserServiceInternalImpl.java
> +    private ConfigurationService configurationService;
Updated to `final`

2023-11-27 18:53 UTC, phuongnq commented on src/main/java/org/craftercms/studio/impl/v2/service/security/internal/UserServiceInternalImpl.java
> +    public UserServiceInternalImpl(UserDAO userDao , ConfigurationService configurationService,
updated

2023-11-27 18:59 UTC, phuongnq commented on src/main/resources/crafter/studio/upgrade/pipelines.yaml
> +          nextVersion: 4.2.0.0
I noticed that we have the same convention for `site-config.xml`: https://github.com/craftercms/studio/blob/develop/src/main/resources/crafter/studio/upgrade/pipelines.yaml#L880 so I added an extra `.0`, or do we prefer to have just 3 number for `permission-mappings.xml`?

2023-11-27 18:59 UTC, phuongnq commented on src/main/java/org/craftercms/studio/impl/v2/utils/spring/security/messaging/StudioMessageSecurityExpressionRoot.java
>              }
This was fixed after merged `develop` into this branch

2023-11-27 20:39 UTC, jmendeza approved these changes

2024-06-20 01:50 UTC, phuongnq commented
Close for now. Will revaluate in 5.0.0

2024-06-20 01:50 UTC, closed without merging