Use RequireSiteExists annotation to check site
craftercms/studio pull request #3430
Opened 2024-01-09 11:06 UTC by phuongnq

https://github.com/craftercms/craftercms/issues/6397

* Use `RequireSiteExists` annotation instead of `siteService.checkSiteExists(site);`
* When a method has `RequireSiteReady`, there is no need to further check site exists since site ready has also check if the site first exists.

2024-01-12 21:25 UTC, jmendeza requested changes

2024-01-12 21:25 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v2/service/content/ContentServiceImpl.java
> +    public boolean contentExists(@ProtectedResourceId(SITE_ID_RESOURCE_ID) @SiteId String siteId,
`SiteId` itself is annotated with `@ProtectedResourceId`. Please validate just `@SiteId` would be enough

2024-01-12 21:25 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v2/service/dependency/DependencyServiceImpl.java
> +    public List<DependencyItem> getDependentItems(@SiteId @ProtectedResourceId(SITE_ID_RESOURCE_ID) String siteId,
@SiteId itself is annotated with @ProtectedResourceId

2024-01-12 21:25 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v2/service/site/SitesServiceImpl.java
> +    public void deleteSite(@SiteId @ProtectedResourceId(SITE_ID_RESOURCE_ID) String siteId) throws ServiceLayerException {
SiteId itself is annotated with @ProtectedResourceId. Please validate just @SiteId would be enough

2024-01-17 03:48 UTC, phuongnq commented on src/main/java/org/craftercms/studio/impl/v2/service/content/ContentServiceImpl.java
> +    public boolean contentExists(@ProtectedResourceId(SITE_ID_RESOURCE_ID) @SiteId String siteId,
Updated to have `@SiteId` only

2024-01-17 03:48 UTC, phuongnq commented on src/main/java/org/craftercms/studio/impl/v2/service/dependency/DependencyServiceImpl.java
> +    public List<DependencyItem> getDependentItems(@SiteId @ProtectedResourceId(SITE_ID_RESOURCE_ID) String siteId,
Updated to have `@SiteId` only

2024-01-17 03:48 UTC, phuongnq commented on src/main/java/org/craftercms/studio/impl/v2/service/site/SitesServiceImpl.java
> +    public void deleteSite(@SiteId @ProtectedResourceId(SITE_ID_RESOURCE_ID) String siteId) throws ServiceLayerException {
Updated to have `@SiteId` only

2024-01-17 16:29 UTC, jmendeza approved these changes

2024-01-17 17:38 UTC, sumerjabri approved these changes

2024-01-17 17:38 UTC, merged