New publish APIs
craftercms/studio pull request #3490
Opened 2024-02-21 00:57 UTC by jmendeza

New publish APIs

2024-02-22 16:24 UTC, sumerjabri requested changes

2024-02-22 16:24 UTC, sumerjabri commented on src/main/api/studio-api.yaml
>          items:
`paths`

2024-02-22 16:24 UTC, sumerjabri commented on src/main/api/studio-api.yaml
> +              commitId:
move to `commitIds` array

2024-02-22 16:24 UTC, sumerjabri commented on src/main/api/studio-api.yaml
> +                items:
`paths`

2024-02-22 16:24 UTC, sumerjabri commented on src/main/api/studio-api.yaml
> +                      commitId:
move to `commitId` array

2024-02-22 16:24 UTC, sumerjabri commented on src/main/api/studio-api.yaml
> +  /api/2/publish/calculate:
`/publish/dependencies`

2024-02-22 19:44 UTC, jmendeza commented on src/main/api/studio-api.yaml
>          items:
Done

2024-02-22 19:44 UTC, jmendeza commented on src/main/api/studio-api.yaml
> +              commitId:
Done

2024-02-22 19:44 UTC, jmendeza commented on src/main/api/studio-api.yaml
> +                items:
Done

2024-02-22 19:44 UTC, jmendeza commented on src/main/api/studio-api.yaml
> +                      commitId:
Done

2024-02-22 19:44 UTC, jmendeza commented on src/main/api/studio-api.yaml
> +  /api/2/publish/calculate:
Done

2024-02-22 22:24 UTC, sumerjabri requested changes
Let's discuss:

I really don't like the mixing of commitId and path based publishing/dep calc, etc. I think we need two root APIs, one around commits and the other paths. The reasons are:

1. Documentation is easier to understand and more meaningful
2. Test automation is better when the params are one and clear (including security and penetration testing)
3. There is no use-case where the user is mixing both, unless via the UI and the UI can unpack a commit ID first and then submit publish by path
4. API aesthetics

LMK your thoughts before I push forward with this.
The change becomes:

- Calc for commitId returns all the files, hard deps, soft deps
- Publish by commitId is the commit ID (maybe plural)
- Publish takes only paths (which may have come by expanding the commitId and submitting files)

2024-02-23 19:41 UTC, jmendeza commented
Added a `requestApproval` param to publish API. If false, user needs publish permission

2024-05-08 19:38 UTC, jmendeza commented
Moved to PR for new feature branch https://github.com/craftercms/studio/pull/3544

2024-05-08 19:38 UTC, closed without merging