Add maxKeys to S3 list API
craftercms/studio pull request #3618
Opened 2024-09-17 05:35 UTC by phuongnq

https://github.com/craftercms/craftercms/issues/6799

2024-11-15 19:48 UTC, jmendeza requested changes

2024-11-15 19:48 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v2/service/aws/s3/AwsS3ServiceImpl.java
> +            if (items.size() >= maxKeys + commonPrefixesCount) {
Why not have a counter for the contents (which are the ones being limited) instead of prefixes?
So condition would be like this:
```
contentsCount >= maxKeys
```

2024-11-19 02:58 UTC, phuongnq commented on src/main/java/org/craftercms/studio/impl/v2/service/aws/s3/AwsS3ServiceImpl.java
> +            if (items.size() >= maxKeys + commonPrefixesCount) {
Refactored the method `listItems` a bit and use `contentsCount`

2024-11-19 18:15 UTC, jmendeza approved these changes

2024-11-19 19:27 UTC, sumerjabri approved these changes

2024-11-19 19:27 UTC, merged