Optimize site creation generated SQL
craftercms/studio pull request #3621
Opened 2024-09-28 00:16 UTC by jmendeza

Optimize site creation generated SQL
https://github.com/craftersoftware/craftercms/issues/1016
https://github.com/craftercms/craftercms/issues/7326

2024-09-29 19:31 UTC, sumerjabri requested changes

2024-09-29 19:31 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/api/v2/repository/ContentRepository.java
> +     * Execute consumers for all site paths for the given site
Can we discuss this one?

2024-09-29 19:31 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
> +    // Max number of items to insert using a single batch
Max items to insert in a single batch

2024-09-29 19:31 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
> +            insertCreateSiteAuditLog(siteId, siteName, blueprintId, creator);
What does this do?

2024-09-29 19:31 UTC, sumerjabri commented on src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
> +            TimeUtils.logExecutionTimeThrowing(() -> {
Let's discuss this.

2024-09-29 19:31 UTC, sumerjabri commented on src/test/java/org/craftercms/studio/impl/v2/repository/blob/BlobAwareContentRepositoryTest.java
> +//        when(localRepositoryV2.getAllSitePaths(SITE)).thenReturn(
Why keep this commented out stuff?

2024-10-02 01:49 UTC, jmendeza commented on src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java
> +    // Max number of items to insert using a single batch
Updated

2024-10-02 01:49 UTC, jmendeza commented on src/test/java/org/craftercms/studio/impl/v2/repository/blob/BlobAwareContentRepositoryTest.java
> +//        when(localRepositoryV2.getAllSitePaths(SITE)).thenReturn(
Updated

2024-10-02 03:09 UTC, sumerjabri approved these changes

2024-10-02 03:10 UTC, merged