Lock with multiple lock keys with the order of the parameters
craftercms/studio pull request #3630
Opened 2024-10-14 04:24 UTC by phuongnq

https://github.com/craftercms/craftercms/issues/7319

2024-10-14 17:32 UTC, jmendeza requested changes
We use the StudioUtils.getSyncFromRepoLockKey in the SyncFromRepositoryTask and DeploymentServiceImpl.
I think what we should do is make sure that we lock sandbox repo whenever we lock sync-from-repo, in the same action.
Let's make StudioUtils.getSyncFromRepoLockKey private. And have a couple helper methods to lock/unlock both keys in the right order.

lockSandboxSync(lockService, siteId)
unlockSandboxSync(lockService, siteId)
Then update DeploymentServiceImpl to call those instead of locking site sync only (the git operations will also lock on sandbox repo, but that will not be an issue since it will be the same thread).
So now no code path can lock sync first and sandbox repo later.

2024-10-15 06:43 UTC, phuongnq commented
I updated per discussed

2024-10-15 07:35 UTC, jmendeza approved these changes

2024-10-15 10:48 UTC, sumerjabri approved these changes

2024-10-15 10:48 UTC, merged